### ISSUE TITLE
Fix `unicode` error while reading xml

### ISSUE THREAD

**Issue by ikus060** [codewatchorg/jnlpdownloader#2]
The line `xmltree = ET.ElementTree(ET.fromstring(r.text))` is failling if the XML contains non ascii char. To fix it: `xmltree = ET.ElementTree(ET.fromstring(r.content))`

**Comment by codewatchorg** [comment]
Fixed with commit https://github.com/codewatchorg/jnlpdownloader/commit/e749a4ce77256e20fc5ce9edc30d67a246a2c946
